### ISSUE TITLE
Heads up on issue with query selector shadow dom

### ISSUE THREAD

**Issue by Georgegriff** [testophobia/testophobia#25]
Hey, saw this package cropped up on dependent list on https://www.npmjs.com/package/query-selector-shadow-dom just wanted to let you know I put some fixes in yesterday that fixes some of the more complex css selectors. 

 I'm not sure how you're using the package but thought would give you a heads up that any version prior to 0.2.3 will have some issues around selector lists and attribute selectors, which should now be fixed

See https://github.com/Georgegriff/query-selector-shadow-dom/issues/2 for details

**Comment by jasongardnerlv** [comment]
@Georgegriff Thanks for the heads-up! 

We'll get it updated

**Comment by srmward** [comment]
Closing issue after merging https://github.com/testophobia/testophobia/pull/26 into master.
